name: a simple + clean agency
favicon: null
layout_spectrum: 0
typography_spectrum: 0.00684
title: Advertising + Branding for Modern Day Commerce
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#111634'
    - '#726056'
    - '#fe9456'
    - '#c9331b'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
